language: node_js

node_js:
  - "8"
  - "10"
  - "12"
script: "npm run-script test-travis"

jobs:
  include:
    - language: node_js
      node_js: node
      script:
        - nyc npm run test
      after_success: "npm run coveralls"