name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  package-lock-lint:
    name: package-lock lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: lint package-lock
        run: npx lockfile-lint --path package-lock.json --allowed-hosts npm --validate-https

  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node: ['14', '16', '18']
    needs: [package-lock-lint]
    name: test (node V${{ matrix.node}})
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests & Collect Coverage
        run: npm run test:coveralls
      - name: Coveralls
        uses: coverallsapp/github-action@master
        if: matrix.node == '18'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
